export const mediaCardModel = {
    shareModal: false,
    showUserPhoto: true,
    isTeachPhysically: true,
    isTeachRemotely: true,
    isOnline: false,
    showApprovedBadge: true,
    showIsOnlineBadge: true,
    shareUrl: '',
    shareText: '',
    cardLink: '',
    username: '',
    genderName: '',
    photoUrl: import.meta.env.VITE_CDN_URL + 'icon-user.png',
    title: '',
    subTitle: '',
    description: '',
    price: '',
    locationName: '',
    totalComment: '',
    createdAt: '',
    requestButtonUrl: ''
}
