export const mediaCardModel = {
    shareModal: false,
    showUserPhoto: true,
    isTeachPhysically: true,
    isTeachRemotely: true,
    isOnline: false,
    showApprovedBadge: true,
    showIsOnlineBadge: true,
    shareUrl: '',
    shareText: '',
    cardLink: '',
    username: '',
    genderName: 'Erkek',
    photoUrl: '/images/icon-user.png',
    title: 'Bahadır Öğretmen',
    subTitle: 'Her seviyeye özel matematik ve geometri dersi',
    description: 'Orta okul ve Lise Takviye-LGS-Üniversite Sınavlarına Hazırlık(TYT-AYT)-KPSS-DGS-ALES ve diğer merkezi sınav seviyelerine özel olarak Matematik-Geometri dersleri ve Eğitim Koçluğu hizmeti verilir. Kaliteli bir MATEMATİK- GEOMETRİ ve dersi egitimi ile rakiplerinizden herzaman bir adım önde olmak elinizde...',
    price: '30 - 40',
    locationName: 'İstanbul, Maltepe',
    totalComment: '10',
    createdAt: '',
    requestButtonUrl: ''
}
