export const requestModel = {
    teacherUuid: '',
    keywordLesson: '',
    keywordLocation: '',
    outsideTurkey: false,
    levelId: '',
    countryId: '',
    countyId: '',
    placeOwn: false,
    placeTeacher: false,
    placeRemote: false,
    budget: [50,200],
    budgetSecret: false,
    genderId: '',
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    message: '',
    responseTypeId: '',
    isAgreementChecked: false
}
