export const searchParamsModel = {
    'page' : 1,
    'pageSize': 12,
    'field': 'searchPoint',
    'order': 'desc',
    'keyword' : '',
    'budget': '',
    'cityObject': null,
    'countyObject': null,
    'subjectObject': null,
    'levelObject': null,
    'categoryObject': null,
    'lessonTypeObject': null,
    'genderObject': null,
}
